crypto_dict={"BTC":"Bitcoin",
"ETH":"Ethereum",
"USDT":"Tether",
"XRP":"XRP",
"DOT":"Polkadot",
"ADA":"Cardano",
"LINK":"Chainlink",
"LTC":"Litecoin",
"BCH":"Bitcoin Cash",
"XLM":"Stellar",
"BNB":"Binance Coin",
"USDC":"USD Coin",
"UNI":"Uniswap",
"WBTC":"Wrapped Bitcoin",
"AAVE":"Aave",
"DOGE":"Dogecoin",
"BSV":"Bitcoin SV",
"EOS":"EOS",
"XMR":"Monero",
"TRX":"TRON",
"XTZ":"Tezos",
"SNX":"Synthetix",
"XEM":"NEM",
"THETA":"THETA",
"ATOM":"Cosmos",
"VET":"VeChain",
"DAI":"Dai",
"NEO":"Neo",
"MKR":"Maker",
"COMP":"Compound",
"CRO":"Crypto.com Coin",
"BUSD":"Binance USD",
"SUSHI":"SushiSwap",
"LEO":"UNUS SED LEO",
"HT":"Huobi Token",
"MIOTA":"IOTA",
"CEL":"Celsius",
"SOL":"Solana",
"EGLD":"Elrond",
"FTT":"FTX Token",
"DASH":"Dash",
"FIL":"Filecoin",
"REV":"Revain",
"ZEC":"Zcash",
"YFI":"yearn.finance",
"AVAX":"Avalanche",
"KSM":"Kusama",
"ETC":"Ethereum Classic",
"ZIL":"Zilliqa",
"ALGO":"Algorand",
"GRT":"The Graph",
"DCR":"Decred",
"WAVES":"Waves",
"LUNA":"Terra",
"VGX":"Voyager Token",
"LRC":"Loopring",
"UMA":"UMA",
"RUNE":"THORChain",
"NEAR":"NEAR Protocol",
"HBAR":"Hedera Hashgraph",
"RENBTC":"renBTC",
"REN":"Ren",
"HEDG":"HedgeTrade",
"CELO":"Celo",
"CRV":"Curve DAO Token",
"CHSB":"SwissBorg",
"1INCH":"1inch",
"OMG":"OMG Network",
"NEXO":"Nexo",
"NANO":"Nano",
"ZRX":"0x",
"BAT":"Basic Attention Token",
"ONT":"Ontology",
"HUSD":"HUSD",
"ICX":"ICON",
"DGB":"DigiByte",
"TUSD":"TrueUSD",
"ZEN":"Horizen",
"BTT":"BitTorrent",
"QNT":"Quant",
"ALPHA":"Alpha Finance Lab",
"RSR":"Reserve Rights",
"FTM":"Fantom",
"QTUM":"Qtum",
"OKB":"OKB",
"STX":"Stacks",
"SC":"Siacoin",
"KNC":"Kyber Network",
"ENJ":"Enjin Coin",
"UST":"TerraUSD",
"IOST":"IOST",
"NXM":"NXM",
"PAX":"Paxos Standard",
"XVG":"Verge",
"MANA":"Decentraland",
"BTCB":"Bitcoin BEP2",
"OCEAN":"Ocean Protocol",
"BNT":"Bancor",
"EWT":"Energy Web Token",
"FLOW":"Flow (Dapper Labs)",
"AMPL":"Ampleforth",
"BAND":"Band Protocol",
"REP":"Augur",
"MATIC":"Matic Network",
"BAL":"Balancer",
"BTG":"Bitcoin Gold",
"RVN":"Ravencoin",
"FUN":"FunFair",
"MAID":"MaidSafeCoin",
"SNT":"Status",
"GNO":"Gnosis",
"CAKE":"PancakeSwap",
"LSK":"Lisk",
"AR":"Arweave",
"HNT":"Helium",
"ANT":"Aragon",
"ABBC":"ABBC Coin",
"TFUEL":"Theta Fuel",
"INJ":"Injective Protocol",
"ZB":"ZB Token",
"CKB":"Nervos Network",
"HOT":"Holo",
"BCD":"Bitcoin Diamond",
"GLM":"Golem",
"NMR":"Numeraire",
"RIF":"RSK Infrastructure Framework",
"UBT":"Unibright",
"CHZ":"Chiliz",
"UTK":"Utrust",
"OXT":"Orchid",
"PAXG":"PAX Gold",
"KAVA":"Kava.io",
"BTS":"BitShares",
"IOTX":"IoTeX",
"TOMO":"TomoChain",
"MONA":"MonaCoin",
"STORJ":"Storj",
"SXP":"Swipe",
"SRM":"Serum",
"CVC":"Civic",
"RLC":"iExec RLC",
"NPXS":"Pundi X",
"KCS":"KuCoin Token",
"BTM":"Bytom",
"CVT":"CyberVein",
"MRPH":"Morpheus.Network",
"KMD":"Komodo",
"ONE":"Harmony",
"ROSE":"Oasis Network",
"VLX":"Velas",
"RDD":"ReddCoin",
"PPT":"Populous",
"SCRT":"Secret",
"AVA":"Travala.com",
"NRG":"Energi",
"ARDR":"Ardor",
"ANKR":"Ankr",
"FET":"Fetch.ai",
"DNT":"district0x",
"ELF":"aelf",
"STEEM":"Steem",
"WICC":"WaykiChain",
"OPIUM":"Opium",
"MFT":"Mainframe",
"YFII":"DFI.Money",
"JST":"JUST",
"WAN":"Wanchain",
"STRAX":"Stratis",
"DX":"DxChain Token",
"NOIA":"Syntropy",
"PNK":"Kleros",
"STAKE":"xDai",
"KP3R":"Keep3rV1",
"XVS":"Venus",
"LOOM":"Loom Network",
"AGI":"SingularityNET",
"KIN":"Kin",
"WAXP":"WAX",
"IRIS":"IRISnet",
"TRAC":"OriginTrail",
"MLN":"Enzyme",
"SYS":"Syscoin",
"SWAP":"TrustSwap",
"POLY":"Polymath",
"HIVE":"Hive",
"LBC":"LBRY Credits",
"ADK":"Aidos Kuneen",
"LTO":"LTO Network",
"DIA":"DIA",
"ETN":"Electroneum",
"TRB":"Tellor",
"ARK":"Ark",
"DIVI":"Divi",
"BZRX":"bZx Protocol",
"AKRO":"Akropolis",
"ADX":"AdEx Network",
"FIRO":"Firo",
"XHV":"Haven Protocol",
"UQC":"Uquid Coin",
"ZCN":"0Chain"}
